using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MathFunctionParser
{
    /** This class represents a node in the evaluation tree
     *  Generated by the Parser
     */
    class ExpressionNode
    {
        // Fields
        private ExpressionNode leftNode;
        private ExpressionNode rightNode;
        public Func<double, double, double> evalFunc;

        // Constructor
        public ExpressionNode(ExpressionNode left, ExpressionNode right)
        {
            leftNode = left;
            rightNode = right;
        }

        // Methods
        public double Evaluate()
        {
            return evalFunc(leftNode.Evaluate(), rightNode.Evaluate());
        }
    }
}
